config/routes.rb
Project::Application.routes.draw do
  resources :pros

   root 'welcome#index'

   get 'users/login' => 'users#login'
   get 'users/logout' => 'users#logout'

   get 'maps' => 'maps#index'
   get 'maps/getAdress' => 'maps#getAdress'

 
   
    get 'admin' => 'admin#index'
   match ':controller(/:action(/:id))', :controller => /admin\/[^\/]+/, :via => :all

   

  

end

app/models/pro.rb
class Pro < ActiveRecord::Base
	validates_presence_of :name, :localhost
	validates_uniqueness_of :name, :message => "项目名称必须唯一", :on => :create
	validates_format_of :url, :localhost,
						:with =>  /(http|https):\/\/(:?).*/ix,
						:message => "请填写合法的项目地址"


end

app/controllers/admin/log_controller.rb
class Admin::LogController < ApplicationController
	layout 'admin'
	before_action :set_pro, only: [:list]

	def initialize
		@nav_id = 'admin-log'
		super
	end

	def index
        @nav_id = 'admin-log'

	end


	def list
		@rows = params[:rows]

	end


	private

	def set_pro

	  begin
	  	@pro = Pro.find(params[:id])
	  rescue
	  	render_not_found
	  end

    end

end

app/controllers/admin/test_controller.rb
class Admin::TestController < ApplicationController

	def index


	end	

end	

app/controllers/admin_controller.rb
class AdminController < ApplicationController
	layout 'admin'
	def index
		
		
	end	

end	

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def loginAdmin
	session[:isAdmin] = true
	session[:user] = {username: 'admin'}
	#session[:user][:username] = 'admin'
  end	

  def logoutAdmin
	session[:isAdmin] = nil
	session[:user] = nil
  end



  def self.rescue_errors
     rescue_from Exception,                            :with => :render_error
     rescue_from RuntimeError,                         :with => :render_error
     rescue_from ActiveRecord::RecordNotFound,         :with => :render_not_found
     rescue_from ActionController::RoutingError,       :with => :render_not_found
     rescue_from ActionController::UnknownController,  :with => :render_not_found
     rescue_from ActionController::UnknownAction,      :with => :render_not_found
  end

  rescue_errors unless Rails.env.development?

  def render_not_found(exception = nil)
    
    
    render :template => "errors/404", :status => 404, :layout => false
  end

  def render_error(exception = nil)
   render :template => "errors/500", :status => 500, :layout => false
  end

end

app/controllers/maps_controller.rb
class MapsController < ApplicationController

	require 'open-uri'
	require 'uri'
  

	def index
		@pros = Pro.all

		@pro_list_adress = []
		@pro_list_ip = []
		@pro_list = []

		urls = []

		#pro_list 

		@pros.each do |item|
			if !item.url.empty?
	
			 @pro_list.push(item)
		   end
    	end
 
	end	


	def getAdress 
			url = params[:url]
			hosturl = URI.parse(url).host
			hosturl ||= url
			if hosturl
				ip = IPSocket.getaddress(hosturl)
				@pro_list_adress = getAdressForIp(ip)
				render :json => @pro_list_adress.to_json
			else 
				render :json => '[]'	
			end
	end	

	

	private

	def getAdressForIp(ip = '')
		api = "https://api.weibo.com/2/location/geo/ip_to_geo.json?ip=#{ip}&access_token=2.00TJ877B0wq4Ihccfb424a92Kww4MB"
		if ip
			response = open(api).read
			data = JSON::parse(response)
			data['geos'] ? data['geos'] : []
		end	
	end	


	def tt
		conn = Faraday.new(:url => api) do |faraday|
			  faraday.request  :url_encoded             # form-encode POST params
			  faraday.response :logger                  # log requests to STDOUT
			  faraday.adapter  Faraday.default_adapter  # make requests with Net::HTTP
			end

			response = conn.get '/', { :ip => ip, :access_token => '2.00TJ877B0wq4Ihccfb424a92Kww4MB' } 

			logger.debug response.body

	end	

	

end

app/controllers/pros_controller.rb
class ProsController < ApplicationController
  before_action :set_pro, only: [:show, :edit, :update, :destroy]

  # GET /pros
  # GET /pros.json
  def index
    @pros = Pro.page(params[:page]).per(20)


  end

  # GET /pros/1
  # GET /pros/1.json
  def show
  end

  # GET /pros/new
  def new
    @pro = Pro.new
  end

  # GET /pros/1/edit
  def edit
  end

  # POST /pros
  # POST /pros.json
  def create
    @pro = Pro.new(pro_params)

    respond_to do |format|
      if @pro.save
        format.html { redirect_to @pro, notice: '新建成功' }
        format.json { render action: 'show', status: :created, location: @pro }
      else
        format.html { render action: 'new' }
        format.json { render json: @pro.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pros/1
  # PATCH/PUT /pros/1.json
  def update
    respond_to do |format|
      if @pro.update(pro_params)
        format.html { redirect_to @pro, notice: '更新成功' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @pro.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pros/1
  # DELETE /pros/1.json
  def destroy
    @pro.destroy
    respond_to do |format|
      format.html { redirect_to pros_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pro
      @pro = Pro.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pro_params
      params.require(:pro).permit(:name, :localhost, :url, :des, :branch, :testip)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def index
		
		
	end	

	def login
		
		@userlogin = params.permit(:username, :pwd)

		if @userlogin[:username] == 'admin' && @userlogin[:pwd] == '123456'
			loginAdmin
			redirect_to pros_url, notice: '登陆成功!'	
		else
			redirect_to pros_url, alert: '登陆失败!'	
		end	
		
		
		#redirect_to pros_url, notice: '登陆成功!'
	end	

	def logout
		logoutAdmin
		redirect_to pros_url, notice: '已经退出!'	
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

	def index
		
	end	


	def login
		
			
	end	

end

app/helpers/application_helper.rb
module ApplicationHelper

	def h_flash_notice(type = '')

			if !flash[:notice].nil?
				   return "<div class='alert alert-success alert-dismissable  fade in'>
				   <button type='button' class='close' data-dismiss='alert' aria-hidden='true'>&times;</button>
				   <strong><span class='glyphicon glyphicon-ok-sign'></span></strong>  
				   #{flash[:notice]}
				   </div>" 	
			end	

			if !flash[:alert].nil?
				   return "<div class='alert alert-warning alert-dismissable  fade in'>
				   <button type='button' class='close' data-dismiss='alert' aria-hidden='true'>&times;</button>
				   <strong><span class='glyphicon glyphicon-ok-sign'></span></strong>  
				   #{flash[:alert]}
				   </div>" 	
			end
	end
	
	def renderTitle(title = '')

		return "<h3 class=text-info>#{title}</h3>"

	end	


	def isActive(path = '')
		request.path =~ /#{path}/i ? 'class=active' : ''
	end	

	def isAdmin?
		!session[:isAdmin].blank?
	end

	def user(key = '')

		if key
			session[:user][key] ? session[:user][key] : ''
		else
			session[:user]	
		end		
	end 


	def getPros
		@pro_list = []
		@pros = Pro.all

		@pros.each do |item|
			if !item.url.empty?
			 @pro_list.push(item)
		   end
    	end

    	"<script>var pro_list = #{@pro_list.to_json};</script>"

	end	

end

app/helpers/maps_helper.rb
module MapsHelper
end

app/helpers/pros_helper.rb
module ProsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/index.html.erb
<div class="row">
    <div class="col-md-12">
        <h2 class="page-title">项目健康监控 <small>健康状态</small></h2>
    </div>
</div>


<!--checkfunction start-->
<div class="row" id='checkfunction'></div>
<!--checkfunction end-->




<script id="healthStatus" type="text/html">
<div class="col-md-3 col-sm-4 col-xs-6">
    <div class="box">
        
        <div class='title'>
        	{{name}}
        </div>

        <div class="row">
            <div class="health_status col-md-1" data-percent="0" data-url='{{url}}'><span>0</span>%</div> 
            <div class='status_show col-md-2'>
                ok!
            </div>
        </div>

    </div>
</div>
</script>

app/views/admin/log/index.html.erb
<div class="row">
    <div class="col-md-8">


        <section class="widget">
            <header>
                <h4>
                    <i class="icon-shopping-cart"></i>
                    项目错误统计
                    <small>
                        php运行错误
                    </small>
                </h4>
            </header>
            <div class="body">
                <table class="table table-striped no-margin sources-table" id='log_trend'>
                    <thead>
                    <tr>
                        <th class="source-col-header">项目名称</th>
                        <th>错误数</th>
                        <th>错误趋势</th>
                        <th class="hidden-xs">所占历史比例 %</th>
                        <th>总错误数</th>
                        <th class="chart-col-header hidden-xs">趋势图</th>
                    </tr>
                    </thead>
                    <tbody>

                    </tbody>
                </table>
            </div>
        </section>


    </div>


</div>


<script id="log_list_tr" type="text/html">
 <tr data-url='{{url}}' data-today='today' data-total='total' data-yesterday='yesterday' data-qs='qs' data-bl='bl' data-qsdata='qsdata'>
    <td><span class="label label-info">
    <a href="{{logListUrl}}" style='color:#fff;' title='{{url}}' target='_blank'>{{name}}</a>
    </span></td>
    <td class='today'>{{today}}</td>
    <td><strong class="qs">{{qs}}</strong></td>
    <td class="hidden-xs bl">{{bl}}</td>
    <td class='total'>{{total}}</td>
    <td class="chart-cell hidden-xs">
        <div class="direct-trend">
        
        </div>
    </td>
</tr>
</script>


<script>
	$(function() {
		Dashboard.log.init();

        $('#forms-collapse').collapse('show');
	});
</script>

app/views/admin/log/list.html.erb
<script>
	var hostUrl = '<%== @pro.url rescue nil%>';
	var rows = '<%== @rows rescue nil%>';
</script>

<% content_for :head_block do %>
<%= javascript_include_tag 'admin/loglist'%>
<% end %>

<script id="log_item" type="text/html">
	<section class="search-result {{type}}_div">
	    <h4>{{type}}</h4>
	    <p class="text-success"><small>{{time}}</small></p>
	    <p>
	    	{{meg}}
	    </p>
	</section>
</script>

<div class="row">
    <div class="col-md-12">
        <h2 class="page-title">Log查看 <small>php错误日志</small></h2>
    </div>
</div>

<div class="row" style='display:none;'>
    <div class="col-md-8 col-md-offset-2">
        <section class="widget">
            <div class="body no-margin">
                <div class="row">
                    <div class="col-md-10 col-md-offset-1">
                        <form class="form-inline form-search no-margin text-align-center" role="form">
                            <div class="input-group">
                                <input type="search" class="form-control" placeholder="Keywords: Node.js, History">
                        <span class="input-group-btn">
                            <button class="btn btn-primary">
                                Search
                            </button>
                        </span>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </section>
    </div>
</div>


<div class="row">
    <div class="col-md-12">
        <section class="widget padding-increased">
            <header>
                <h4>
                    日记结果
                </h4>
                <hr>
            </header>
            <div id='log_list' class="body no-margin"></div>

            <div class="text-align-center">
                    <ul class="pagination">
                        <li class="disabled"><a href="#">Prev</a></li>
                        <li class="active"><a href="#">1</a></li>
                        <li><a href="#">2</a></li>
                        <li><a href="#">3</a></li>
                        <li><a href="#">4</a></li>
                        <li><a href="#">5</a></li>
                        <li><a href="#">Next</a></li>
                    </ul>
                </div>


        </section>
    </div>
</div>

<script>
    $(function() {

        if (hostUrl) {
            loglist.init(hostUrl);      
        }

    });
</script>

app/views/common/_errordb.erb
<% if obj.errors.any? %>
    <div id="error_explanation" class="alert alert-danger fade in">
      <span class='glyphicon glyphicon-remove-circle'></span>
      
      <h3><%= obj.errors.count.to_s + ": 错误" %> </h3>

      <ul>
      <% obj.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>

    </div>
  <% end %>

app/views/common/_indexheder.html.erb
<nav class="navbar navbar-default" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="/">项目监控</a>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav">
      <li <%== isActive 'pros' %> ><a href="/pros">项目查看</a></li>
      <li <%== isActive 'maps' %> ><a href="/maps" target='_self'>项目分布</a></li>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">监控 <b class="caret"></b></a>
        <ul class="dropdown-menu">
          <li><a href="/admin" target='_blank'>项目状态</a></li>
          <li><a href="/admin/log" target='_blank'>日记查看</a></li>

          <li class="divider"></li>
          <li><a href="#">建设中</a></li>
          <li class="divider"></li>
          <li><a href="#">建设中</a></li>
        </ul>
      </li>
    </ul>
    
    <ul class="nav navbar-nav navbar-right">
      
      <% if isAdmin?%>
       <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= user :username%>, 管理 <b class="caret"></b></a>
        <ul class="dropdown-menu">
          <li><a href="#">Action</a></li>
          <li><a href="#">Another action</a></li>

          <li class="divider"></li>
          <li><a href="<%= users_logout_path%>"><%= t 'views.login.out' %></a></li>
        </ul>
      </li>

      <%else%>
        <li><a href="#loginModal"  data-toggle="modal"><%= t 'views.login.in' %></a></li>
      <%end%>

    </ul>

    <form class="navbar-form navbar-right" role="search">
      <div class="form-group">
        <input type="text" class="form-control" placeholder="Search">
      </div>
      <button type="submit" class="btn btn-default">Submit</button>
    </form>

  </div><!-- /.navbar-collapse -->
</nav>

    
<%== h_flash_notice %>  



<!-- Modal -->
<div class="modal fade" id="loginModal" tabindex="-1" role="dialog" aria-labelledby="管理员登陆" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">

      <form class="form-horizontal" role="form" action="<%= users_login_path %>" method='GET'>
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 class="modal-title" id="myModalLabel">管理员登陆</h4>
        </div>
        <div class="modal-body">
        
         
            <div class="form-group">
              <label for="inputEmail3" class="col-sm-2 control-label">用户名</label>
              <div class="col-sm-10">
                <input type="text" class="form-control" id="username" placeholder="用户名" name="username">
              </div>
            </div>
            <div class="form-group">
              <label for="inputPassword3" class="col-sm-2 control-label">密码</label>
              <div class="col-sm-10">
                <input type="password" class="form-control" id="pwd" placeholder="密码" name="pwd">
              </div>
            </div>
      

        </div>
        <div class="modal-footer">
    
          <button type="submit" class="btn btn-primary">登陆</button>
        </div>
      </form>

    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Project</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= stylesheet_link_tag    params[:controller] %>		

  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= yield :head_block %>
  <%= javascript_include_tag  params[:controller] + '/' + params[:controller] %>


  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
  <div class="row">
    <div class="col-md-12">
<%= render :partial => 'common/indexheder' %>
<%= yield %>

    </div>
  </div>
</div>

</body>
</html>

app/views/layouts/navleft.html.erb
<nav id="sidebar" class="sidebar nav-collapse collapse">
    <ul id="side-nav" class="side-nav">
        <li class="panel">
            <a href="/admin" target="_self"><i class="icon-home"></i> <span class="name">项目健康监控</span></a>
        </li>
        <li class="panel">
            <a class="accordion-toggle collapsed" data-toggle="collapse" data-parent="#side-nav" href="/#forms-admin-log"><i class="icon-edit"></i> <span class="name">日记查看</span></a>
            <ul id="forms-admin-log" class="panel-collapse collapse">
                <li><a href="<%== url_for :controller => 'admin/log', :action => 'index' %>" target="_blank">项目错误统计</a></li>


            </ul>
        </li>
        <li class="panel">
            <a class="accordion-toggle collapsed" data-toggle="collapse" data-parent="#side-nav" href="http://demo.okendoken.com/#stats-collapse"><i class="icon-bar-chart"></i> <span class="name">Statistics</span></a>
            <ul id="stats-collapse" class="panel-collapse collapse">
                <li><a href="http://demo.okendoken.com/stat_statistics.html">Stats</a></li>
                <li><a href="http://demo.okendoken.com/stat_charts.html">Charts</a></li>
                <li><a href="http://demo.okendoken.com/stat_realtime.html">Realtime</a></li>
            </ul>
        </li>
        <li class="panel">
            <a class="accordion-toggle collapsed" data-toggle="collapse" data-parent="#side-nav" href="http://demo.okendoken.com/#ui-collapse"><i class="icon-magic"></i> <span class="name">User Interface</span></a>
            <ul id="ui-collapse" class="panel-collapse collapse">
                <li><a href="http://demo.okendoken.com/ui_buttons.html">Buttons</a></li>
                <li><a href="http://demo.okendoken.com/ui_dialogs.html">Dialogs</a></li>
                <li><a href="http://demo.okendoken.com/ui_icons.html">Icons</a></li>
                <li><a href="http://demo.okendoken.com/ui_tabs.html">Tabs</a></li>
                <li><a href="http://demo.okendoken.com/ui_accordion.html">Accordion</a></li>
            </ul>
        </li>
        <li class="panel">
            <a class="accordion-toggle collapsed" data-toggle="collapse" data-parent="#side-nav" href="http://demo.okendoken.com/#components-collapse"><i class="icon-bookmark-empty"></i> <span class="name">Components</span></a>
            <ul id="components-collapse" class="panel-collapse collapse">
                <li><a href="http://demo.okendoken.com/component_calendar.html">Calendar</a></li>
                <li><a href="http://demo.okendoken.com/component_maps.html">Maps</a></li>
                <li><a href="http://demo.okendoken.com/component_gallery.html">Gallery</a></li>
                <li><a href="http://demo.okendoken.com/component_fileupload.html">Fileupload</a></li>
            </ul>
        </li>
        <li class="panel">
            <a class="accordion-toggle collapsed" data-toggle="collapse" data-parent="#side-nav" href="http://demo.okendoken.com/#tables-collapse"><i class="icon-table"></i> <span class="name">Tables</span></a>
            <ul id="tables-collapse" class="panel-collapse collapse">
                <li><a href="http://demo.okendoken.com/tables_static.html">Static</a></li>
                <li><a href="http://demo.okendoken.com/tables_dynamic.html">Dynamic</a></li>
            </ul>
        </li>
        <li>
            <a href="http://demo.okendoken.com/grid.html"><i class="icon-reorder"></i> <span class="name">Grid</span></a>
        </li>
        <li class="panel">
            <a class="accordion-toggle collapsed" data-toggle="collapse" data-parent="#side-nav" href="http://demo.okendoken.com/#special-collapse"><i class="icon-asterisk"></i> <span class="name">Special</span></a>
            <ul id="special-collapse" class="panel-collapse collapse">
                <li><a href="http://demo.okendoken.com/special_search.html">Search</a></li>
                <li><a href="http://demo.okendoken.com/special_invoice.html">Invoice</a></li>
                <li><a href="http://demo.okendoken.com/special_inbox.html">Inbox <span class="label label-important">3</span></a></li>
                <li><a href="http://demo.okendoken.com/login.html">Login</a></li>
                <li><a href="http://demo.okendoken.com/special_404.html">404</a></li>
                <li><a href="http://demo.okendoken.com/landing.html">Landing</a></li>
                <li><a href="http://demo.okendoken.com/white/index.html">White <i class="icon-external-link-sign"></i></a></li>
            </ul>
        </li>
        <li class="visible-xs">
            <a href="http://demo.okendoken.com/login.html"><i class="icon-signout"></i> <span class="name">Sign Out</span></a>
        </li>
    </ul>
    <div id="sidebar-settings" class="settings">


    <button type="button" data-value="icons" class="btn-icons btn btn-transparent btn-sm">Icons</button>
    <button type="button" data-value="auto" class="btn-auto btn btn-transparent btn-sm">Auto</button>

</div>
</nav>

<script>
    var nav_id = '<%== @nav_id rescue nil%>';
    $(function() {
        if (nav_id) {
            $('#side-nav > li').removeClass('active');
            $('#forms-' + nav_id).closest('li').addClass('active');
            $('#forms-' + nav_id).collapse('show');
        }

    });


</script>

app/views/maps/index.html.erb
<% content_for :head_block do %>
<%= javascript_include_tag 'googlemap', 'GMaps'%>
<% end %>



<div id='prolist' class="list-group">
	<a href="javascript:void(0);" class="list-group-item active" id='resetCenter'>
    	项目
  	</a>
</div>


<div class="panel panel-default">
  <div class="panel-body" id="mapsdiv">
    
  	<div class="progress progress-striped active">
	  <div class="progress-bar progress-bar-info" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width: 100%;">
	    <span class="sr-only">100% Complete</span>
	  </div>
	</div>
    
  </div>
</div>


<script>
var pro_list = <%== @pro_list.to_json %>;
</script>

app/views/pros/common/_tr3.html.erb
<tr class="">
  <td class="col-xs-3"><%= pro.name %></td>
  <td class="col-xs-1"><%= pro.branch %></td>
  <td class="col-xs-3"><%= pro.localhost %></td>


  <td class="<%if isAdmin? %>col-xs-3<%else%>col-xs-4<%end%>"><%= pro.url %></td>


  <td class="text-center col-xs-2">
    <%= link_to '查看', pro, :class =>'btn btn-default btn-sm'%>

    <%if isAdmin? %>
    <%= link_to '编辑', edit_pro_path(pro), :class =>'btn btn-primary btn-sm'%>  
    <%= link_to '删除', pro, method: :delete, data: { confirm: 'Are you sure?' }, :class =>'btn btn-danger btn-sm'%>
    <%end%>
    
  
  </td>

</tr>

app/views/pros/edit.html.erb
<%== renderTitle 'Editing pro'%>

<%= render 'form' %>

<%= link_to 'Show', @pro %> |
<%= link_to 'Back', pros_path %>

app/views/pros/index.html.erb
<%== renderTitle 'Listing pros'%>

<%if isAdmin? %>
<a class="btn btn-primary" href="<%= new_pro_path %>"><i class="icon-pencil icon-white"></i> 增加项目</a>
<%end%>

<br>
<br>


<table class="table table-striped table-bordered table-hover">
  <thead>
    <tr>
      <th>项目名称</th>
      <th>项目分支</th>
      <th>测试地址</th>
      <th>线上地址</th>

      <th>编辑</th>
     
    </tr>
  </thead>

  <tbody>

    <%if @pros.empty?%>
      <tr class=info>
        <td colspan=6 class="text-center">
          无数据
        </td>
      </tr>

    <%end%>
    
    <%= render :partial => "pros/common/tr3", :collection => @pros, :as => :pro%>

  </tbody>
</table>

<%= paginate @pros %>

app/views/pros/new.html.erb
<%== renderTitle 'New pro'%>

<%= render 'form' %>

<%= link_to 'Back', pros_path %>

app/views/pros/show.html.erb
<%== renderTitle 'show pro'%>

<form class="form-horizontal">

	<div class="form-group">
	<label for="" class="col-sm-2 control-label">项目名称</label>

	<div class="col-sm-10">
		<%= @pro.name %>
	</div>
	</div>

	

	<div class="form-group">
	<label for="" class="col-sm-2 control-label">测试地址</label>

	<div class="col-sm-10">
		<%= @pro.localhost %>
	</div>
	</div>

	<div class="form-group">
	<label for="" class="col-sm-2 control-label">测试Ip</label>

	<div class="col-sm-10">
		<%= @pro.testip %>
	</div>
	</div>

	<div class="form-group">
	<label for="" class="col-sm-2 control-label">线上地址</label>

	<div class="col-sm-10">
		<%= @pro.url %>
	</div>
	</div>

	<div class="form-group">
	<label for="" class="col-sm-2 control-label">分支名称</label>

	<div class="col-sm-10">
		<%= @pro.branch %>
	</div>
	</div>

	<div class="form-group">
	<label for="" class="col-sm-2 control-label">备注</label>

	<div class="col-sm-10">
		<%= @pro.des %>
	</div>
	</div>
</form>


<%if isAdmin?%>
<%= link_to 'Edit', edit_pro_path(@pro) %> |
<%end%>

<%= link_to 'Back', pros_path %>

app/views/welcome/index.html.erb
<div class="row">
  <div class="col-sm-6 col-md-4">
    <div class="thumbnail">
      <img data-src="holder.js/300x200" alt="...">
      <div class="caption">
        <h3>流程监控</h3>
        <p>流程监控流程监控流程监控流程监控流程监控流程监控流程监控流程监控</p>
        <p><a href="#" class="btn btn-primary" role="button"><%= t('views.home.jr')%></a></p>
      </div>
    </div>
  </div>

  <div class="col-sm-6 col-md-4">
    <div class="thumbnail">
      <img data-src="holder.js/300x200" alt="...">
      <div class="caption">
        <h3>数据监控</h3>
        <p>数据监控数据监控数据监控数据监控数据监控数据监控数据监控数据监控数据监控数据监控</p>
        <p><a href="#" class="btn btn-primary" role="button"><%= t('views.home.jr')%></a></p>
      </div>
    </div>
  </div>

  <div class="col-sm-6 col-md-4">
    <div class="thumbnail">
      <img data-src="holder.js/300x200" alt="...">
      <div class="caption">
        <h3>用户监控</h3>
        <p>用户监控用户监控用户监控用户监控用户监控用户监控用户监控用户监控用户监控用户监控用户监控</p>
        <p><a href="#" class="btn btn-primary" role="button"><%= t('views.home.jr')%></a></p>
      </div>
    </div>
  </div>

</div>